apiVersion: v1
kind: Service
metadata:
 name: mynodeport
 annotations:
   service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: public
   service.kubernetes.io/ibm-load-balancer-cloud-provider-zone: "<region>"
spec:
 type: NodePort
 selector:
   app: sample-room-golang
 ports:
  - protocol: TCP
    port: 3000